import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import JsonLd from "@/components/json-ld";
import { breadcrumbSchema, createPageMetadata } from "@/lib/seo";
import { FinalCta } from "@/components/page-sections";
import styles from "../homepage2.module.css";
import section from "@/components/page-sections.module.css";
import { roofingSources } from "@/lib/roofing-answers";

export const metadata: Metadata = createPageMetadata({ title: "Roofing Quotes & Repairs Guide", description: "Compare roofing quotes in BC: written scope, materials, concealed damage, payment, warranty, and contractor checks, with RCABC and WorkSafeBC sources.", path: "/roofing-guide" });

export default function RoofingGuide() {
  return <main id="main-content" tabIndex={-1}><JsonLd data={breadcrumbSchema([{name:"Home",path:"/"},{name:"Homeowner guide",path:"/roofing-guide"}])} />
    <div className={`${styles.sectionShell} ${section.section}`}><nav className={styles.breadcrumbs} aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><span>Homeowner guide</span></nav>
      <article className={section.article}>
        <p>For homeowners in Cloverdale & Surrey</p><h1>Make a clearer decision about your roof.</h1><p>You do not need to know roofing terminology to ask useful questions. Start with the problem, compare the work included, and agree how surprises will be handled.</p>
        <nav className={section.jumpLinks} aria-label="In this guide"><a href="#quick-answer">Quote essentials</a><a href="#repair-or-replace">Repair or replace</a><a href="#compare-quotes">Compare quotes</a><a href="#contractor-checks">Contractor checks</a><a href="#prepare">Prepare for a visit</a><a href="#handover">After the work</a></nav>
        <section id="quick-answer"><h2>What should a roofing quote include in BC?</h2><p>A useful roofing quote identifies the work area, removal and disposal, materials, flashing and ventilation work, concealed-damage pricing, access arrangements, schedule, payment terms, taxes, exclusions, and warranty responsibilities. Request a written scope from each contractor so you can compare the same work.</p><p>The <a href={roofingSources.rcabc.url}>Roofing Contractors Association of BC (RCABC)</a> recommends written specifications, payment terms, details of reused materials, and a sample warranty. The checklist below expands those questions for your assessment.</p></section>
        <section id="repair-or-replace"><h2>Repair or replacement?</h2><p>The decision depends on how widespread the problem is and the condition of the remaining roof. Age helps provide context, but it should not be the only reason given for a replacement.</p>
          <table className={section.comparison}><caption>Questions to discuss during an assessment</caption><thead><tr><th scope="col">What you notice</th><th scope="col">What to ask</th></tr></thead><tbody><tr><th scope="row">One recurring leak</th><td>Has the actual entry point been identified? Is the surrounding roof still serviceable?</td></tr><tr><th scope="row">Wear in several areas</th><td>Would repairs address the wider deterioration, or only the symptoms?</td></tr><tr><th scope="row">An aging cedar roof</th><td>What condition is the deck in, and what preparation would a conversion require?</td></tr><tr><th scope="row">Unknown roof history</th><td>What can an inspection establish, and what will remain concealed or uncertain?</td></tr></tbody></table>
          <p>A leak alone does not establish that a replacement is needed. If two contractors disagree, <a href={roofingSources.rcabc.url}>RCABC suggests a roof observer’s inspection</a> to help inform the decision.</p><p><Link href="/services/roof-repair">Read about roof repair</Link> or <Link href="/services/roof-replacement">see what a replacement involves</Link>.</p>
        </section>
        <section id="compare-quotes"><h2>Compare what the quote covers.</h2><p>A lower total can reflect a different scope. Ask each contractor to make these items explicit so you can compare like for like.</p><ol>
          <li><strong>The work area.</strong> Which roof sections, additions, garages, or other buildings are included?</li>
          <li><strong>Removal and preparation.</strong> What is being removed, retained, inspected, and disposed of?</li>
          <li><strong>The roof system.</strong> Which materials, underlayment, flashing, and ventilation work are specified?</li>
          <li><strong>Concealed damage.</strong> What deck repairs are allowed for, and how will extra work be documented, priced, and approved?</li>
          <li><strong>Access and protection.</strong> Where will materials and waste be placed, and how will entrances, landscaping, and neighbouring property be protected?</li>
          <li><strong>Timing and payment.</strong> What is the estimated schedule, what might change it, and when are payments due?</li>
          <li><strong>Warranty and follow-up.</strong> Which product and workmanship terms apply, who provides them, and how do you report a concern?</li>
          <li><strong>Exclusions and total.</strong> Are disposal, taxes, gutters, interior repairs, or other related items included or excluded?</li>
        </ol><p>Ask for clarification before agreeing to work. A product brochure, verbal promise, and written project scope serve different purposes.</p></section>
        <section id="prepare"><h2>Make the assessment more useful.</h2><p>Have the address and building details ready. Note when the problem began, where it appears, and whether it changes with rain or wind. Include previous reports or repair records if you have them.</p><ul><li>Take photos only from a safe position on the ground or indoors.</li><li>Identify the affected building if the property has more than one roof.</li><li>Mention gates, shared driveways, limited parking, pets, and access restrictions.</li><li>Confirm any owner, strata, or property-manager authorization needed for access.</li><li>State a purchase deadline or timing constraint before arranging the visit.</li></ul><p className={section.note}>You do not need to climb onto the roof to prepare a request. Describe what you can see and let the assessment establish safe access.</p><Link className={styles.textLink} href="/services/roof-inspection">What a roof inspection can cover<ArrowRight size={18} aria-hidden="true" /></Link></section>
        <section id="handover"><h2>Keep the details after the work.</h2><p>Keep the agreed scope, any approved changes, product information, invoices, and applicable warranty documents together. Ask about maintenance, what was left outside the scope, and how to raise a follow-up question.</p><p>If an issue returns, record when it appeared and where it is visible. That information is more useful than guessing at the cause.</p></section>
        <section id="contractor-checks"><h2>How can you check a roofing contractor?</h2><p>Ask for the business’s legal name, local business licence, references, insurance certificate, and WorkSafeBC clearance details. Match the documents to the contractor named in your proposal. <a href={roofingSources.rcabc.url}>RCABC’s contractor questions</a> explain which evidence to request.</p><p>A <a href={roofingSources.worksafe.url}>WorkSafeBC clearance letter</a> confirms registration and premium-payment standing. Check the dates and business named in the letter. Discuss your circumstances with WorkSafeBC if you are unsure what coverage is needed.</p><h3>Check the proposed product, too</h3><p>Ask for the manufacturer’s current installation instructions and warranty for the exact product being quoted. For example, <a href={roofingSources.iko.url}>IKO publishes installation and warranty documents</a> in its resource library. A manufacturer reference here does not identify the product that will be installed on your roof.</p><p className={section.note}>Source links checked 7 September 2026. These independent resources support the homeowner guidance; they do not certify or endorse this website or a proposed contractor.</p></section>
      </article>
    </div><FinalCta title="Put your roof questions to us." /></main>;
}
